#!/bin/sh
# husky

# Hook created by Husky
#   Version: 1.3.1
#   At: 2019-6-20 13:06:48
#   See: https://github.com/typicode/husky#readme

# From npm package
#   Name: husky
#   Directory: undefined
#   Homepage: https://github.com/typicode/husky#readme

npm version patch

